// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_eH2pz2X-6pwjc6IC24bJWyqtcjsR_c',
    appId: '1:67248834813:web:a2d49c6d94cb8c20ee9694',
    messagingSenderId: '67248834813',
    projectId: 'smec-9067c',
    authDomain: 'smec-9067c.firebaseapp.com',
    storageBucket: 'smec-9067c.appspot.com',
    measurementId: 'G-1EXH7Z5SGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABhXyUSM_AVeisxQP30Yeqai1ZkPspr0I',
    appId: '1:67248834813:android:19653a95a054267eee9694',
    messagingSenderId: '67248834813',
    projectId: 'smec-9067c',
    storageBucket: 'smec-9067c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACsislLDKhm2x-LMIVTTh1vU5QUu61J8Q',
    appId: '1:67248834813:ios:8c438bac486e1881ee9694',
    messagingSenderId: '67248834813',
    projectId: 'smec-9067c',
    storageBucket: 'smec-9067c.appspot.com',
    iosBundleId: 'com.example.smec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACsislLDKhm2x-LMIVTTh1vU5QUu61J8Q',
    appId: '1:67248834813:ios:31dd2aa0190ebf04ee9694',
    messagingSenderId: '67248834813',
    projectId: 'smec-9067c',
    storageBucket: 'smec-9067c.appspot.com',
    iosBundleId: 'com.example.smec.RunnerTests',
  );
}
